server:
  maxThreads: 32
  minThreads: 8
  maxQueuedRequests: 1024
  rootPath: '/api/*'
  applicationConnectors:
  - type: http
    port: 9126
  adminConnectors:
  - type: http
    port: 9127

kafka:
  host: localhost
  port: 9092
  topic: firecrest-messages

elasticSearch:
  host: localhost
  port: 9300
