server:
  maxThreads: 32
  minThreads: 8
  maxQueuedRequests: 1024
  rootPath: '/api/*'
  applicationConnectors:
  - type: http
    port: 9123
  adminConnectors:
  - type: http
    port: 9124

bindHost: localhost
tcpMessagePort: 9125

kafka:
  host: localhost
  port: 9022
  topic: firecrest-messages