server:
  maxThreads: 32
  minThreads: 8
  maxQueuedRequests: 1024
  rootPath: '/api/*'
  applicationConnectors:
  - type: http
    port: 9126
  adminConnectors:
  - type: http
    port: 9127

kafka:
  host: localhost
  port: 9092
  topic: firecrest-messages

logging:
  appenders:
    - type: file
      currentLogFilename: /var/log/firecrest/indexer.log
      archivedLogFilenamePattern: /var/log/firecrest/indexer-%d-%i.log.gz
      archivedFileCount: 10
      maxFileSize: 50MB
    - type: console
#      threshold: ALL
#      timeZone: UTC
      target: stdout

elasticSearch:
  host: localhost
  port: 9300
